project:
  type: website
  output-dir: docs
  
website:
  title: "My Personal Website for STAT 37815"
  navbar:
    tools:
      - icon: github
        href: https://github.com/will-nahley/will-nahley.github.io
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: united
    mainfont: "'Open Sans', sans-serif"
    # css: my-style.css
    # toc: true